### ISSUE TITLE
Quantization support

### ISSUE THREAD

**Issue by cafaxo** [cafaxo/Llama2.jl#10]
We should investigate how difficult it is to add quantization support.
It would be great if we could run the Llama2 7B model on a machine with 8GB RAM.

**Comment by svilupp** [comment]
I'd say the first goal should be to even load Llama2 7B, but once that works, the Q4_0 quantization as they have it in ggml should be pretty straightforward.

**Comment by cafaxo** [comment]
I have it loading already -- working on the quantization vecdot routines right now.

**Comment by svilupp** [comment]
That’s awesome! I was looking to power that with Metal.jl - are you on a M1/M2 as well?

**Comment by cafaxo** [comment]
Jup, on an M1 Air.
