### ISSUE TITLE
How to find and download a suitable GGMLV3 model?

### ISSUE THREAD

**Issue by RainerHeintzmann** [cafaxo/Llama2.jl#27]
I tried finding and downloading the `llama-2-7b-chat.ggmlv3.q4_K_S.bin` file from HuggingFace, but was unable to do so.
What does one need to do to actually obtain that bin file? I tried the `model.savetensor` from the repo, but this does not seem to be the right format.

**Comment by cafaxo** [comment]
GGML support was removed in favor of the new GGUF format.
GGUF models can be downloaded from https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/tree/main.
