### ISSUE TITLE
Reproduce temp=0 llama.cpp results with some consistency. 

### ISSUE THREAD

**Issue by Sixzero** [cafaxo/Llama2.jl#28]
We need to find a way to detect what could cause the differences between the two solutions. 

The task is to have the same or near similar results at temp=0. We made some tests with the new `.gguf` files since it got so huge adoption.

Llama2.jl test:
```
using Llama2
model = load_gguf_model("/path/to/llama-2-7b-chat.Q4_K_S.gguf");
sample(model, "Tim was happy."; temperature = 0.0f0)
```

llama.cpp test .gguf test:
`./main -m /Users/lukasmayrhofer/Downloads/llama-2-7b-chat.Q4_K_S.gguf --samplers "temp" --temp 0 -p "Tim was happy."`

Current Llama2.jl results:
```
Tim was happy. Einzelnes, but he was also very proud of his son. He had always known that Tim was special, and he was thrilled to see him finally getting the recognition he deserved.\nAs the two of them sat in the stands, watching the game, Tim couldn't help but feel a sense of pride and joy. He was so grateful to have" ⋯ 667 bytes ⋯ ". \"I'm lucky to have you too.\"\nAs they walked out of the restaurant, Tim felt a sense of contentment and happiness. He knew that he had a wonderful son, and he was grateful for every moment they spent together. He was proud of Tim, and he knew that he would always be there to support and encourage him, no matter what.
```

Current llama.cpp results:
```
Tim was happy.
He had just received a new job offer and he was excited to start his new career. He had been searching for a new opportunity for months, and now it seemed like all his hard work had paid off.
As he walked into the office building, he couldn't help but feel a sense of pride. He had worked hard to get where he was, and he knew that this new job would be a great opportunity for him.
Tim took a deep breath as he entered the office. He was greeted by a friendly receptionist who offered him a warm smile. "Hello there," she said. "Welcome to Tim's new workplace."
Tim felt a sense of excitement as he walked through the office. He couldn't wait to meet his new colleagues and start working on his new projects. He knew that this was going to be a great opportunity for him, and he was eager to get started. [end of text]
```

We need to find an efficient way to know what could cause the differences between the two.

**Comment by krishvishal** [comment]
Would something like the following: https://github.com/google/gemma.cpp/issues/23 be happening here?

**Comment by cafaxo** [comment]
Exactly. It seems that quantizing the hidden state to q8_0 is not a good idea (see https://github.com/ggerganov/llama.cpp/issues/4755; it is unfortunate that the bot closed this).
We should rewrite our quantized vecdot routines to do the calculations in fp16 or fp32. The challenge here is to not degrade the speed of the vecdots too much.

**Comment by cafaxo** [comment]
This is now fixed with the new vecdot routines: https://github.com/cafaxo/Llama2.jl/commit/587d270a36e44012205b77e6443e2d1e1450f8a2.
